disabled_rules:
- trailing_whitespace
- conditional_returns_on_newline
- force_unwrapping
- implicitly_unwrapped_optional
- multiple_closures_with_trailing_closure
- identifier_name

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- empty_count
- explicit_init
- fatal_error_message
- first_where
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- valid_docs

excluded:
- Pods/
- Carthage/
- vendor/bundle

line_length: 300
