# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Develop Branches build test"
  lane :test do |options|

    # 実行時プロパティ xcargs に渡す値を生成
    xcargs = ""
    if options[:QIITA_CLIENT_ID] != nil
      xcargs += "QIITA_CLIENT_ID=#{options[:QIITA_CLIENT_ID]} "
    end
    if options[:QIITA_CLIENT_SECRET] != nil
      xcargs += "QIITA_CLIENT_SECRET=#{options[:QIITA_CLIENT_SECRET]} "
    end
    if options[:QIITA_ACCESS_TOKEN] != nil
      xcargs += "QIITA_ACCESS_TOKEN=#{options[:QIITA_ACCESS_TOKEN]} "
    end

    scan(project: "Swiita.xcodeproj", destination: "platform=iOS Simulator,name=iPhone 8,OS=13.6", scheme: "Swiita", xcargs: xcargs)
  end
end
