name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: XCode version select
      run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 
      
    - name: Run tests
      run: swift test -v
