name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug -enableCodeCoverage=YES build 
      
    - name: Run tests
      env:
        QIITA_CLIENT_ID: ${{ secrets.QIITA_CLIENT_ID }}
        QIITA_CLIENT_SECRET: ${{ secrets.QIITA_CLIENT_SECRET }}
        QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}

      run: xcodebuild -scheme Swiita test -destination "name=iPhone 8" QIITA_CLIENT_ID=${QIITA_CLIENT_ID} QIITA_CLIENT_SECRET=${QIITA_CLIENT_ID} QIITA_ACCESS_TOKEN=${QIITA_ACCESS_TOKEN}
